[[ -s "${HOME}/.zprezto/init.zsh" ]] && source "${HOME}/.zprezto/init.zsh"

export HISTFILE="${HOME}"/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000
export HISTIGNORE=' '
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history

setopt auto_cd
setopt auto_pushd
setopt cdable_vars
setopt pushd_ignore_dups
setopt pushd_silent
setopt pushd_to_home

setopt always_to_end
setopt auto_menu
setopt auto_name_dirs
setopt auto_param_keys
setopt auto_param_slash
setopt auto_remove_slash
setopt complete_aliases
setopt complete_in_word
setopt list_ambiguous
setopt listpacked
unsetopt menu_complete

setopt brace_ccl
setopt extended_glob
setopt long_list_jobs
setopt multios
setopt prompt_subst

setopt interactive_comments
setopt rc_quotes
setopt short_loops
unsetopt correct
unsetopt correct_all
unsetopt clobber
unsetopt flowcontrol

autoload -U compinit promptinit colors
compinit -i
promptinit
colors

for conf in $(find "${HOME}/.dotfiles/shell/zsh/" -name '*.zsh'); do
    source "${conf}"
done

[[ -f "${HOME}/.zshrc.local" ]] && source "${HOME}/.zshrc.local"

return 0
