#! /usr/bin/env bash

bspc config border_width                    2
bspc config split_ratio                     0.50
bspc config borderless_monocle              true
bspc config gapless_monocle                 false
bspc config auto_alternate                  true
bspc config auto_cancel                     true
bspc config window_gap                      16
bspc config normal_border_color             "#1D1F21"
bspc config focused_border_color            "#949494"
bspc config presel_border_color             "#FF8700"
bspc config private_border_color            "#D75F5F"
bspc config sticky_border_color             "#689D6A"

bspc config focus_follows_pointer		true

bspc rule -a Firefox desktop=^1
bspc rule -a plugin-container floating=true
bspc rule -a pavucontrol follow=true floating=true center=true
bspc rule -a lxappearance floating=true center=true
bspc rule -a lxtask floating=true center=true
bspc rule -a gcolor2 floating=true center=true
bspc rule -a sxiv floating=true center=true
bspc rule -a Conky sticky=true manage=false lower=true
bspc rule -a Steam desktop=^5
bspc rule -a ncview floating=true

bspc monitor -d I II III IV V
