#! /bin/sh
#
# Example panel for LemonBoy's bar

while read -r line ; do
    case $line in
        S*)
            sys_infos="%{r}${line#?}%{F-}"
            ;;
        T*)
		title="%{A:launcher:} %{F#005E8D87 B#001D1F21} >%{F-}"
            ;;
        W*)
            wm_infos="%{c}"
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    [OFU]*)
                        # active desktop
                        wm_infos="$wm_infos%{F#00C5C8C6 B#001D1F21}  %{F-}"
                        ;;
                    o*)
                        # inactive but occupied desktop
                        wm_infos="$wm_infos%{F#005E8D87 B#001D1F21}  %{F-}"
                        ;;
                    f*)
                        # inactive desktop
                        wm_infos="$wm_infos%{F#00707880 B#001D1F21}  %{F-}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos%{F#00A54242 B#001D1F21}%  %{F-}"
                        ;;
                    L*)
#                        # layout
#                        layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
#                        wm_infos="$wm_infos \\b4\\f0$layout%{B-}%{F-}"
#                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "$title$wm_infos$sys_infos"
done
