#!/bin/bash

# WIFI ICONS
# 

QUAL=`iwconfig wlp3s0 | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $3}'`
MAX=`iwconfig wlp3s0 | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $4}'`
PERC=`echo $QUAL*100/$MAX | bc -q`

ICON=""
case $PERC in
	[0-16])
		ICON=""
	;;
	[17-33])
		ICON=""
	;;
	[34-50]*)
		ICON=""
	;;
	[51-67]*)
		ICON=""
	;;
	[68-84]*)
		ICON=""
	;;
	*)
		ICON=""
	;;
esac

echo "%{F#5E8D87}$ICON"
