#! /usr/bin/env bash

xset +fp /usr/share/fonts/local
xset +fp /usr/share/fonts/misc
xset fp rehash
xset -dpms
xset s off
xset -b

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources &

wmname LG3D &
thunar --daemon &
xautolock -locker 'i3lock -c 262626' -time 20 -corners 0-00 &
start-pulseaudio-x11 &
numlockx on &
udiskie &
nm-applet &
hsetroot -full ~/pic/wallpapers/cymac.png
