#! /bin/sh

bspc monitor -d I II III IV V

bspc config border_width                1
bspc config window_gap                  8
bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config auto_alternate              true
bspc config auto_cancel                 true
bspc config top_padding                 15
bspc config normal_border_color         "#1D1F21"
bspc config focused_border_color        "#5E8D87"
bspc config presel_border_color         "#707880"

bspc config focus_follows_pointer		true

bspc rule -a Firefox desktop=^1
bspc rule -a plugin-container floating=true
bspc rule -a smplayer floating=on
bspc rule -a pavucontrol follow=true floating=true center=true
bspc rule -a lxappearance floating=true center=true
bspc rule -a lxtask floating=true center=true
bspc rule -a gcolor2 floating=true center=true
bspc rule -a sxiv floating=true center=true
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a Steam desktop=^5
