#! /usr/bin/env bash

active_window=$(xdotool getactivewindow)
active_desktop=$(xdotool get_desktop)
window_list="/tmp/hide.${active_desktop}"

usage() {
    echo 'Usage: hide [OPTION]'
    echo 'Options:'
    echo '  -H        hide active window'
    echo '  -S        show hidden window'
}

push() {
    xdotool windowunmap "${1}"
    echo "${1}" >> "${window_list}"
}

pop() {
    local window=$(tail -n1 "${window_list}")
    head -n-1 "${window_list}" | sponge "${window_list}"
    xdotool windowmap "${window}"
}

while getopts ':S :H' opt; do
    case "${opt}" in
        S)
            pop
            ;;
        H)
            push "${active_window}"
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

[[ "${OPTIND}" -eq 1 ]] && usage && exit 1
