#! /usr/bin/env bash

active_window=$(xdotool getactivewindow)
active_desktop=$(xdotool get_desktop)
window_list="/tmp/hide.${active_desktop}"

usage() {
    cat <<-EOL
Usage: hide [OPTION]
Options:
    -H          hide active window
    -S          show hidden window

    -h          displays this help message
EOL
}

push() {
    xdotool windowunmap "${1}"
    echo "${1}" >> "${window_list}"
}

pop() {
    local window=$(tail -n1 "${window_list}")
    head -n-1 "${window_list}" | sponge "${window_list}"
    xdotool windowmap "${window}"
}

while getopts ':S :H :h' opt; do
    case "${opt}" in
        S)
            pop
            ;;
        H)
            push "${active_window}"
            ;;
        h)
            usage
            exit 0
            ;;
        :)
            echo -e "-${OPTARG} requires an argument"
            usage
            exit 1
            ;;
        \?)
            echo -e "-${OPTARG} is not a valid option"
            usage
            exit 1
            ;;
    esac
done

[[ "${OPTIND}" -eq 1 ]] && usage
exit 0
