#! /usr/bin/env bash

pandoc --toc -s -S --mathjax="mathjax/MathJax.js?config=TeX-AMS_HTML-full" \
    -H "${NOTES}/config/note.css" --template="${NOTES}/config/template.html" \
    -f 'markdown+pandoc_title_block+simple_tables+table_captions+yaml_metadata_block' \
    -t html5 "${1}" > "$(basename -s '.md' ${1}).html"
