#! /usr/bin/env bash

notes_root_dir="${NOTES}/notes"
notes_config_dir="${NOTES}/config"

usage() {
    echo -e 'USAGE:'
    echo -e '   note CMD [ARGS]'
}

list() {
    if [[ -z "${1}" ]]; then
        local name='*'
    else
        local name='*.md'
    fi
    find "${1:-${notes_root_dir}}" -maxdepth 1 -mindepth 1 -name "${name}" -not -path '*/\.*' -exec basename {} \; | sort
}

tag() {
    ag "${1}" -G md$ --nocolor -l "${2:-"${notes_root_dir}"}" | xargs -n1 basename | sort
}

new() {
    set -o noclobber
    local path="${notes_root_dir}/${2:-general}"
    [[ ! -d "${path}" ]] && mkdir -p "${path}"
    [[ "${1}" =~ .*.md ]] && sed -e "s|%date%|$(date '+%d/%m/%Y')|" "${notes_config_dir}/template.md" > "${path}/${1}"
}

main() {
    local cmd="${1}"
    local -a args="${@:2}"
    case "${cmd:-'list'}" in
        'list')
            list ${args}
            ;;
        'tag')
            tag ${args}
            ;;
        'new')
            new ${args}
            ;;
        *)
            usage
            exit 1
            ;;
    esac
}

main "${1}" "${@:2}"
