#! /usr/bin/env bash

notes_root_dir="${NOTES}/notes"
notes_config_dir="${NOTES}/config"

usage() {
    echo -e 'Usage:'
    echo -e '   note <command>'
}

list() {
    if [[ -z "${1}" ]]; then
        local name='*'
    else
        local name='*.md'
    fi
    find "${notes_root_dir}/${1:-}" -maxdepth 1 -mindepth 1 -name "${name}" -not -path '*/\.*' -exec basename {} \; | sort
}

tag() {
    ag "${1}" -G md$ --nocolor -l "${2:-"${notes_root_dir}"}" | parallel 'basename {}' | sort
}

new() {
    set -o noclobber
    local path="${notes_root_dir}/${1:-general}"
    [[ ! -d "${path}" ]] && mkdir -p "${path}"
    [[ "${2}" =~ .*.md ]] && sed -e "s|%date%|$(date '+%d/%m/%Y')|" "${notes_config_dir}/template.md" > "${path}/${2}"
}

edit() {
    [[ ! -z "${1}" ]] && local path="${notes_root_dir}/${1}/${2}.md"
    [[ -z "${1}" ]] && local path="${notes_root_dir}/general/${1}.md"
    [[ -e "${path}" ]] && vim "${path}"
}

main() {
    local cmd="${1}"
    local -a args=${@:2}
    case "${cmd:-'list'}" in
        'list')
            list ${args}
            ;;
        'tag')
            tag ${args}
            ;;
        'new')
            new ${args}
            ;;
        'edit')
            edit ${args}
            ;;
        *)
            usage
            exit 1
            ;;
    esac
}

main "${1}" "${@:2}"
exit 0
