#! /usr/bin/env bash

[[ -f "${HOME}/.pop/config" ]] && source "${HOME}/.pop/config"

POP_FG="${POP_FG:-#FF1D1F21}"
POP_BG="${POP_BG:-#FF999999}"
POP_DURATION="${POP_DURATION:-2s}"
POP_X="${POP_X:-1734}"
POP_Y="${POP_Y:-6}"
POP_H="${POP_H:-20}"
POP_W="${POP_W:-180}"
POP_GEOMETRY="${POP_GEOMETRY:-"${POP_WIDTH}x${POP_HEIGHT}+${POP_X}+${POP_Y}"}"
POP_FONT="${POP_FONT:--*-ttyp0-medium-r-*--14-*-*-*-*-*-iso10646-1}"

while getopts ':x: :y: :w: :h: :b: :f: :d:' opt; do
    case "${opt}" in
        x)
            POP_X="${OPTARG}"
            ;;
        y)
            POP_Y="${OPTARG}"
            ;;
        w)
            POP_W="${OPTARG}"
            ;;
        h)
            POP_H="${OPTARG}"
            ;;
        f)
            POP_FG="${OPTARG}"
            ;;
        b)
            POP_BG="${OPTARG}"
            ;;
        d)
            POP_DURATION="${OPTARG}"
            ;;
        \?)
            echo "invalid option: -${OPTARG}" >&2
            exit 1
            ;;
        :)
            echo "required argument: -${OPTARG}" >&2
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

(echo -e "${@}"; sleep "${POP_DURATION}") | bar -g "${POP_W}x${POP_H}+${POP_X}+${POP_Y}" -F "${POP_FG}" -B "${POP_BG}" -f "${POP_FONT}" &
