#! /usr/bin/env bash

usage() {
    cat <<-EOL
Usage: pop [OPTION]
Options:
    -X          pop x position
    -Y          pop y position
    -W          pop width
    -H          pop height
    -F          pop foreground
    -B          pop background
    -D          pop duration

    -h          displays this help message
EOL
}

[[ -f "${HOME}/.pop/config" ]] && source "${HOME}/.pop/config"

POP_FG="${POP_FG:-#FF1D1F21}"
POP_BG="${POP_BG:-#FF999999}"
POP_DURATION="${POP_DURATION:-2s}"
POP_X="${POP_X:-1734}"
POP_Y="${POP_Y:-6}"
POP_H="${POP_H:-20}"
POP_W="${POP_W:-180}"
POP_GEOMETRY="${POP_GEOMETRY:-"${POP_WIDTH}x${POP_HEIGHT}+${POP_X}+${POP_Y}"}"
POP_FONT="${POP_FONT:--*-ttyp0-medium-r-*--14-*-*-*-*-*-iso10646-1}"

while getopts ':X: :Y: :W: :H: :B: :F: :D: :h' opt; do
    case "${opt}" in
        X)
            POP_X="${OPTARG}"
            ;;
        Y)
            POP_Y="${OPTARG}"
            ;;
        W)
            POP_W="${OPTARG}"
            ;;
        H)
            POP_H="${OPTARG}"
            ;;
        F)
            POP_FG="${OPTARG}"
            ;;
        B)
            POP_BG="${OPTARG}"
            ;;
        D)
            POP_DURATION="${OPTARG}"
            ;;
        h)
            usage
            exit 0
            ;;
        :)
            echo -e "-${OPTARG} requires an argument"
            usage
            exit 1
            ;;
        \?)
            echo -e "-${OPTARG} is not a valid option"
            usage
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

(echo -e "${@}"; sleep "${POP_DURATION}") | bar -g "${POP_W}x${POP_H}+${POP_X}+${POP_Y}" -F "${POP_FG}" -B "${POP_BG}" -f "${POP_FONT}" &
