#! /usr/bin/env bash

usage() {
    cat <<-EOL
Usage: vol [OPTION]
Options:
    -U          increase volume
    -D          decrease volume
    -S          set volume
    -B          print bar formatted string
    -E          print current volume

    -h          displays this help message
EOL
}

while getopts ':U :D :S: :B :E :h' opt; do
    case "${opt}" in
        U)
            pulseaudio-ctl up
            ;;
        D)
            pulseaudio-ctl down
            ;;
        S)
            pulseaudio-ctl set ${OPTARG}
            ;;
        B)
            [[ -f "${HOME}/.pop/config" ]] && source "${HOME}/.pop/config"
            volume=$(amixer get Master 2> /dev/null | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p' | uniq)
            volume_bar="——————————"
            n=$(( (${volume%.*} + 5) / 10 ))

            echo -e -D 1 -B "${POP_BG}" "%{c}%{F${POP_HI}}${volume_bar:0:${n}}%{F${POP_FG}}${volume_bar:${n}:${#volume_bar}}"
            ;;
        E)
            volume=$(amixer get Master 2> /dev/null | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p' | uniq)
            printf '%03d\n' "${volume}" 2> /dev/null
            ;;
        h)
            usage
            exit 0
            ;;
        :)
            echo -e "-${OPTARG} requires an argument"
            usage
            exit 1
            ;;
        \?)
            echo -e "-${OPTARG} is not a valid option"
            usage
            exit 1
            ;;
    esac
done

[[ "${OPTIND}" -eq 1 ]] && usage
exit 0
