#! /usr/bin/env bash

cd $(dirname $0)
source $(dirname $)/panel_config

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "${PANEL_FIFO}" ] && rm "${PANEL_FIFO}"
mkfifo "${PANEL_FIFO}"

bspc control --subscribe > "${PANEL_FIFO}" &
echo 'T' > "${PANEL_FIFO}" &
conky -c $(dirname $)/panel_conky > "${PANEL_FIFO}" &

cat ${PANEL_FIFO} \
    | ./panel_bar \
    | bar \
    -F "${COLOUR_FOREGROUND}" \
    -B "${COLOUR_BACKGROUND}" \
    -g "${PANEL_GEOMETRY}"

wait
