#! /usr/bin/env bash

volume=$(printf '%03d' $(amixer get Master | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p' | uniq))
battery=$(printf '%03d' $(battery | awk '{ print $2 }'))
date=$(date +'%H:%M %d/%m/%y')

echo -e "${volume} ${battery} ${date}"
